In [1]:
import pandas as pd 
import numpy as np

In [2]:
#2
airports = pd.read_csv('https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat', header = None)
routes = pd.read_csv('https://raw.githubusercontent.com/jpatokal/openflights/master/data/routes.dat', header = None)

In [3]:
airports.columns = ['id', 'name', 'city', 'country', 'IATA', 'ICAO', 'Latitude', 'Longitude', 'altitude', 'timezone', 'DST',
                   'tz db', 'type', 'source']
routes.columns = ['airline', 'airline ID', 'source airport', 'source airport ID', 'destination airport',
                 'destination airport ID', 'codeshare', 'stops', 'equipment']

airports.head(25)

,id,name,city,country,IATA,ICAO,Latitude,Longitude,altitude,timezone,DST,tz db,type,source
0,1,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081690,145.391998,5282,10,U,Pacific/Port_Moresby,airport,OurAirports
1,2,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20,10,U,Pacific/Port_Moresby,airport,OurAirports
2,3,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826790,144.296005,5388,10,U,Pacific/Port_Moresby,airport,OurAirports
3,4,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239,10,U,Pacific/Port_Moresby,airport,OurAirports
4,5,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.443380,147.220001,146,10,U,Pacific/Port_Moresby,airport,OurAirports
5,6,Wewak International Airport,Wewak,Papua New Guinea,WWK,AYWK,-3.583830,143.669006,19,10,U,Pacific/Port_Moresby,airport,OurAirports
6,7,Narsarsuaq Airport,Narssarssuaq,Greenland,UAK,BGBW,61.160500,-45.425999,112,-3,E,America/Godthab,airport,OurAirports
7,8,Godthaab / Nuuk Airport,Godthaab,Greenland,GOH,BGGH,64.190903,-51.678101,283,-3,E,America/Godthab,airport,OurAirports
8,9,Kangerlussuaq Airport,Sondrestrom,Greenland,SFJ,BGSF,67.012222,-50.711603,165,-3,E,America/Godthab,airport,OurAirports
9,10,Thule Air Base,Thule,Greenland,THU,BGTL,76.531197,-68.703201,251,-4,E,America/Thule,airport,OurAirports
10,11,Akureyri Airport,Akureyri,Iceland,AEY,BIAR,65.660004,-18.072701,6,0,N,Atlantic/Reykjavik,airport,OurAirports
11,12,Egilsstaðir Airport,Egilsstadir,Iceland,EGS,BIEG,65.283302,-14.401400,76,0,N,Atlantic/Reykjavik,airport,OurAirports
12,13,Hornafjörður Airport,Hofn,Iceland,HFN,BIHN,64.295601,-15.227200,24,0,N,Atlantic/Reykjavik,airport,OurAirports
13,14,Húsavík Airport,Husavik,Iceland,HZK,BIHU,65.952301,-17.426001,48,0,N,Atlantic/Reykjavik,airport,OurAirports
14,15,Ísafjörður Airport,Isafjordur,Iceland,IFJ,BIIS,66.058098,-23.135300,8,0,N,Atlantic/Reykjavik,airport,OurAirports
15,16,Keflavik International Airport,Keflavik,Iceland,KEF,BIKF,63.985001,-22.605600,171,0,N,Atlantic/Reykjavik,airport,OurAirports
16,17,Patreksfjörður Airport,Patreksfjordur,Iceland,PFJ,BIPA,65.555801,-23.965000,11,0,N,Atlantic/Reykjavik,airport,OurAirports
17,18,Reykjavik Airport,Reykjavik,Iceland,RKV,BIRK,64.129997,-21.940599,48,0,N,Atlantic/Reykjavik,airport,OurAirports
18,19,Siglufjörður Airport,Siglufjordur,Iceland,SIJ,BISI,66.133301,-18.916700,10,0,N,Atlantic/Reykjavik,airport,OurAirports
19,20,Vestmannaeyjar Airport,Vestmannaeyjar,Iceland,VEY,BIVM,63.424301,-20.278900,326,0,N,Atlantic/Reykjavik,airport,OurAirports
20,21,Sault Ste Marie Airport,Sault Sainte Marie,Canada,YAM,CYAM,46.485001,-84.509399,630,-5,A,America/Toronto,airport,OurAirports
21,22,Winnipeg / St. Andrews Airport,Winnipeg,Canada,\N,CYAV,50.056400,-97.032501,760,-6,A,America/Winnipeg,airport,OurAirports
22,23,Halifax / CFB Shearwater Heliport,Halifax,Canada,\N,CYAW,44.639702,-63.499401,144,-4,A,America/Halifax,airport,OurAirports
23,24,St. Anthony Airport,St. Anthony,Canada,YAY,CYAY,51.391899,-56.083099,108,-3.5,A,America/St_Johns,airport,OurAirports
24,25,Tofino / Long Beach Airport,Tofino,Canada,YAZ,CYAZ,49.079833,-125.775583,80,-8,A,America/Vancouver,airport,OurAirports

In [4]:
routes.head(10)

,airline,airline ID,source airport,source airport ID,destination airport,destination airport ID,codeshare,stops,equipment
0,2B,410,AER,2965,KZN,2990,NaN,0,CR2
1,2B,410,ASF,2966,KZN,2990,NaN,0,CR2
2,2B,410,ASF,2966,MRV,2962,NaN,0,CR2
3,2B,410,CEK,2968,KZN,2990,NaN,0,CR2
4,2B,410,CEK,2968,OVB,4078,NaN,0,CR2
5,2B,410,DME,4029,KZN,2990,NaN,0,CR2
6,2B,410,DME,4029,NBC,6969,NaN,0,CR2
7,2B,410,DME,4029,TGK,\N,NaN,0,CR2
8,2B,410,DME,4029,UUA,6160,NaN,0,CR2
9,2B,410,EGO,6156,KGD,2952,NaN,0,CR2

# 1)Ошибка заключается в том, что в датафрейме есть аэропорты, у которых не определен часовой пояс, но как это возможно? (в каком-то другом измерении находятся)
## Как минимум это проблемные данные

In [5]:
airports[airports['timezone'] == '\\N']

,id,name,city,country,IATA,ICAO,Latitude,Longitude,altitude,timezone,DST,tz db,type,source
6981,11743,La Grande-4 Airport,La Grande-4,Canada,YAH,CYAH,53.754700,-73.675301,1005,\N,\N,\N,airport,OurAirports
6982,11744,Alert Bay Airport,Alert Bay,Canada,YAL,CYAL,50.582199,-126.916000,240,\N,\N,\N,airport,OurAirports
6983,11745,Liverpool South Shore Regional Airport,Liverpool,Canada,\N,CYAU,44.230301,-64.856102,321,\N,\N,\N,airport,OurAirports
6984,11747,Nipawin Airport,Nipawin,Canada,\N,CYBU,53.332500,-104.008003,1220,\N,\N,\N,airport,OurAirports
6985,11748,Centralia / James T. Field Memorial Aerodrome,Centralia,Canada,YCE,CYCE,43.285599,-81.508301,824,\N,\N,\N,airport,OurAirports
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7693,14106,Rogachyovo Air Base,Belaya,Russia,\N,ULDA,71.616699,52.478298,272,\N,\N,\N,airport,OurAirports
7694,14107,Ulan-Ude East Airport,Ulan Ude,Russia,\N,XIUW,51.849998,107.737999,1670,\N,\N,\N,airport,OurAirports
7695,14108,Krechevitsy Air Base,Novgorod,Russia,\N,ULLK,58.625000,31.385000,85,\N,\N,\N,airport,OurAirports
7696,14109,Desierto de Atacama Airport,Copiapo,Chile,CPO,SCAT,-27.261200,-70.779198,670,\N,\N,\N,airport,OurAirports
7697,14110,Melitopol Air Base,Melitopol,Ukraine,\N,UKDM,46.880001,35.305000,0,\N,\N,\N,airport,OurAirports

# 2)Ошибкой назвать сложно, но все перечисленные значения являются данными авиабаз учебных, военных и тп. , а тип имеют "аэропорт"
## По сути не соответствие с действительностью, из такого объекта обычный гражданский навряд ли вылетит , в отличие от аэропорта

In [6]:
airports[airports['name'].str.endswith('Base')].append(airports[airports['name'].str.startswith('Base')])

C:\Users\User\AppData\Local\Temp\ipykernel_4152\2958432643.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  airports[airports['name'].str.endswith('Base')].append(airports[airports['name'].str.startswith('Base')])

,id,name,city,country,IATA,ICAO,Latitude,Longitude,altitude,timezone,DST,tz db,type,source
9,10,Thule Air Base,Thule,Greenland,THU,BGTL,76.531197,-68.703201,251,-4,E,America/Thule,airport,OurAirports
285,288,Sidi Ahmed Air Base,Bizerte,Tunisia,\N,DTTB,37.245398,9.791450,20,1,E,Africa/Tunis,airport,OurAirports
286,289,Remada Air Base,Remada,Tunisia,\N,DTTD,32.306198,10.382100,1004,1,E,Africa/Tunis,airport,OurAirports
297,300,Beauvechain Air Base,Beauvechain,Belgium,\N,EBBE,50.758598,4.768330,370,1,E,Europe/Brussels,airport,OurAirports
298,301,Kleine Brogel Air Base,Kleine Brogel,Belgium,\N,EBBL,51.168301,5.470000,200,1,E,Europe/Brussels,airport,OurAirports
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7695,14108,Krechevitsy Air Base,Novgorod,Russia,\N,ULLK,58.625000,31.385000,85,\N,\N,\N,airport,OurAirports
7697,14110,Melitopol Air Base,Melitopol,Ukraine,\N,UKDM,46.880001,35.305000,0,\N,\N,\N,airport,OurAirports
2488,2620,Base Aérea de Santos Airport,Santos,Brazil,SSZ,SBST,-23.928057,-46.299721,10,-3,S,America/Sao_Paulo,airport,OurAirports
6411,8953,Base Aérea Airport,Anapolis,Brazil,\N,SBAN,-16.229200,-48.964298,3731,-3,S,America/Sao_Paulo,airport,OurAirports
7168,11931,Base de Aviação de Taubaté Airport,Taubaté,Brazil,QHP,SBTA,-23.040100,-45.515999,1908,\N,\N,\N,airport,OurAirports

# 3) Теоретически самолет мог вылететь из одного аэропорта и вернуться в него же (из-за плохой погоды, например). Но все же, странно
## Пол неточности

In [7]:
routes[routes['destination airport'] == routes['source airport']]

,airline,airline ID,source airport,source airport ID,destination airport,destination airport ID,codeshare,stops,equipment
33276,IL,10121,PKN,3910,PKN,3910,NaN,0,AT7

# 4) Здесь проблема заключается в том, что source airport ID(destination airport ID) в routes является id в airports, но мы видим, что для одного и того же кода IATA в airports айди есть, а в routes его нет
# То есть они говорят, что аэропорт в базе числиться и не числиться одновременно
## Сильно.

In [8]:
r1 = routes[routes['source airport ID'] == '\\N']
r2 = routes[routes['destination airport ID'] == '\\N']

r1 = r1[['source airport', 'source airport ID']]
r1 = r1.merge(airports[['IATA', 'id']], left_on = 'source airport', right_on = 'IATA')
r1 = r1[['source airport', 'IATA', 'id', 'source airport ID']]

r1

    source airport IATA     id source airport ID
0              TGK  TGK   6932                \N
1              KCK  KCK   6922                \N
2              PQM  PQM  13334                \N
3              PBZ  PBZ    839                \N
4              PBZ  PBZ    839                \N
..             ...  ...    ...               ...
151            TZL  TZL   6947                \N
152            TZL  TZL   6947                \N
153            TGP  TGP   8341                \N
154            THX  THX   8340                \N
155            JKR  JKR   3124                \N

[156 rows x 4 columns]

In [9]:
r2 = r2[['destination airport', 'destination airport ID']]
r2 = r2.merge(airports[['IATA', 'id']], left_on = 'destination airport', right_on = 'IATA')
r2 = r2[['destination airport', 'IATA', 'id', 'destination airport ID']]
 
r2

    destination airport IATA     id destination airport ID
0                   TGK  TGK   6932                     \N
1                   KCK  KCK   6922                     \N
2                   PQM  PQM  13334                     \N
3                   PBZ  PBZ    839                     \N
4                   HYD  HYD  12087                     \N
..                  ...  ...    ...                    ...
147                 TZL  TZL   6947                     \N
148                 TZL  TZL   6947                     \N
149                 TGP  TGP   8341                     \N
150                 THX  THX   8340                     \N
151                 JKR  JKR   3124                     \N

[152 rows x 4 columns]

# 5) Здесь ошибка серьезнее. Если загрузить координаты аэропортов из надежного источника, можно заметить сильную разницу с нашим исходным датасетом про аэропорты. ~80 аэропортов с неправильными данными (в зависимости от задаваемой погрешности)
## Как так-то

In [10]:
da = pd.read_excel('apinfo.ru.xls') #тут нужен будет файл apinfo.ru.xls (скинул)

In [11]:
da = da.merge(airports[['IATA', 'country', 'Latitude', 'Longitude', 'name']], left_on = 'iata_code', right_on = 'IATA')

In [12]:
da = da[['iata_code' ,'name_eng', 'Longitude', 'longitude', 'Latitude', 'latitude']]

In [13]:
da['longitude'] = da['longitude'].astype(str)
da['longitude'] = da['longitude'].astype(float)
da['latitude'] = da['latitude'].astype(str)
da['Longitude'] = da['Longitude'].astype(float)
da['latitude'] = da['latitude'].astype(float)
da['Latitude'] = da['Latitude'].astype(float)

In [14]:
da.columns = ['IATA', 'name', 'наша longitude', 'правильная longitude', 'наша latitude', 'правильная latitude']

In [15]:
pogresh = 10
da[(abs(da['правильная longitude'] - da['наша longitude']) >= pogresh) | 
   (abs(da['наша latitude'] - da['правильная latitude']) >= pogresh)]

,IATA,name,наша longitude,правильная longitude,наша latitude,правильная latitude
10,AAP,Andrau Airpark,-95.588303,-55.596111,29.722500,72.886944
19,ABB,RAF Station,6.665278,-1.316667,6.204167,51.690556
43,ACJ,Anuradhapura,80.427902,-84.188848,8.301490,32.110799
325,AYO,Ayolas,-56.854064,33.750000,-27.370554,-27.000000
344,BAR,Baker Aaf,110.454775,-176.516667,19.138240,0.216667
...,...,...,...,...,...,...
5315,YFJ,Snare Lake,-114.077002,-74.780000,64.190804,46.409444
5415,YOA,Ekati,-110.614998,25.257500,64.698898,37.394444
5491,YSQ,Spring Island,124.550178,-1.783333,44.938114,59.450000
5621,ZKP,Kasompe,150.888900,27.893950,65.748500,-12.572778
5658,ZZV,Zanesville,-81.892097,0.000000,39.944401,39.944447

# 6) Уже личная придирка. Реализовано кривовато, но если присмотреться, сверяясь со свежими данными, вмдим, что некоторые аэропорты из нашего датасета сегодня называются уже немного по-другому¶
## Кажется несерьезным, но если, например, нам нужно будет на основе airports составить какую-нибудь статистику уже в связке с обнавленными данными, обращаться по имени аэропорта становится затруднительным

In [16]:
kiki = pd.read_html('https://ucsol.ru/tamozhennoe-oformlenie/v-aeroportakh-uslugi-tamozhennogo-brokera/airport-codes-oa-oz')
kiki = kiki[1]

In [18]:
kiki.columns = ['IATa', 'dasd', 'air_name', 'das']
kiki = kiki[['IATa', 'air_name']]

In [21]:
kiki = kiki.merge(airports[['IATA', 'name']], left_on = 'IATa', right_on = 'IATA')

In [23]:
kiki[kiki['name'] != kiki['air_name']]

,IATa,air_name,IATA,name
0,OAA,Forward Operating Base Shank,OAA,Shank Air Base
2,OAH,Shindand Air Base,OAH,Shindand Airport
3,OAI,Bagram Airfield,OAI,Bagram Air Base
4,OAJ,Albert J. Ellis Airport,OAJ,Albert J Ellis Airport
5,OAK,Oakland International Airport,OAK,Metropolitan Oakland International Airport
...,...,...,...,...
173,OXF,Oxford Airport (London Oxford Airport),OXF,Oxford (Kidlington) Airport
180,OYP,"Saint-Georges-de-l""Oyapock Airport",OYP,Saint-Georges-de-l'Oyapock Airport
184,OZH,Zaporizhia International Airport,OZH,Zaporizhzhia International Airport
185,OZP,Morón Air Base,OZP,Moron Air Base
186,OZR,Cairns Army Airfield,OZR,Cairns AAF (Fort Rucker) Air Field